# Generated by Django 3.2.15 on 2022-10-08 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_alter_blogcomments_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Blog.post'),
        ),
    ]
